#!/bin/bash

echo "=========================================="
echo "    Bundle ID 检查工具"
echo "=========================================="
echo ""
echo "当前项目的 Bundle ID："
echo "Dream-making.LifeCoach"
echo ""
echo "=========================================="
echo "请在 App Store Connect 中确认："
echo "=========================================="
echo ""
echo "1. 登录 https://appstoreconnect.apple.com"
echo "2. 进入 [我的App] → [人生教练]"
echo "3. 查看应用信息中的 Bundle ID"
echo ""
echo "如果显示：Dream-making.LifeCoach"
echo "  ✅ 一致！会更新到同一个应用"
echo ""
echo "如果显示其他Bundle ID："
echo "  ⚠️  不一致！需要修改Xcode项目的Bundle ID"
echo ""
echo "=========================================="

